package com.your_app_name.presentation.viewmodels // Adjust package name as needed

import androidx.compose.runtime.mutableStateOf
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.your_app_name.domain.models.Sale // Assuming Sale data class exists
import com.your_app_name.domain.models.SaleItem // Assuming SaleItem data class exists
import com.your_app_name.domain.repository.SaleRepository // Assuming SaleRepository interface exists
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import javax.inject.Inject

// Define a simple SavingState sealed class for now
sealed class SavingState {
    object Idle : SavingState()
    object Saving : SavingState()
    object Success : SavingState()
    data class Error(val message: String) : SavingState()
}

@HiltViewModel
class AddSaleViewModel @Inject constructor(
    private val saleRepository: SaleRepository // Inject SaleRepository
) : ViewModel() {

    // Mutable states for the new sale data
    var newSaleDate: MutableState<Long> = mutableStateOf(System.currentTimeMillis()) // Timestamp
    var newSaleClientId: MutableState<Int?> = mutableStateOf(null) // Placeholder for client ID
    var newSaleItems: MutableState<List<SaleItem>> = mutableStateOf(emptyList())

    // State for saving process
    private val _savingState = MutableStateFlow<SavingState>(SavingState.Idle)
    val savingState: StateFlow<SavingState> = _savingState.asStateFlow()

    // Functions to update the new sale data
    fun updateSaleDate(timestamp: Long) {
        newSaleDate.value = timestamp
    }

    fun updateClientId(clientId: Int) {
        newSaleClientId.value = clientId
    }

    fun addItemToSale(item: SaleItem) {
        newSaleItems.value = newSaleItems.value + item
    }

    fun updateSaleItemQuantity(itemId: Int, quantity: Int) {
        newSaleItems.value = newSaleItems.value.map {
            if (it.id == itemId) it.copy(quantity = quantity) else it
        }
    }

    fun removeSaleItem(itemId: Int) {
        newSaleItems.value = newSaleItems.value.filter { it.id != itemId }
    }

    // Function to save the new sale
    fun saveSale() {
        _savingState.value = SavingState.Saving
        viewModelScope.launch {
            try {
                // Create the Sale object from the current state
                val newSale = Sale(
                    id = 0, // ID will be generated by the database
                    clientId = newSaleClientId.value ?: -1, // Handle null client ID
                    saleDate = newSaleDate.value,
                    items = newSaleItems.value,
                    totalAmount = newSaleItems.value.sumOf { it.quantity * it.priceAtSale } // Calculate total
                )
                saleRepository.insertSale(newSale) // Call the repository to insert
                _savingState.value = SavingState.Success
            } catch (e: Exception) {
                _savingState.value = SavingState.Error(e.localizedMessage ?: "Unknown error")
            }
        }
    }
}